PREFIX powla: <http://purl.org/powla/powla.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
prefix lilacorpora: <http://lila-erc.eu/ontologies/lila_corpora/>
prefix lila: <http://lila-erc.eu/ontologies/lila/>
prefix UDanteSynFunction: <http://lila-erc.eu/data/corpora/DanteSearch/id/UDsynFunction/>
prefix ITTBSynFunction: <http://lila-erc.eu/data/corpora/ITTB/id/synFunction/>

# Use the endpoint "corpora"
# Given a the lexical base of a lemma, find all the lemmas sharing the same lexical base in a document

SELECT ?sameBaseLemmaLabel ?docTitle
WHERE {
  VALUES ?doc {<XXX>}
  service <https://lila-erc.eu/sparql/lemmaBank/query> {
  <http://lila-erc.eu/data/id/lemma/88705> lila:hasBase ?base .
        ?sameBaseLemma lila:hasBase ?base.                             
  
  }
  

  ?token rdf:type powla:Terminal;
         lila:hasLemma ?sameBaseLemma .
  ?token lilacorpora:hasCitStructure/powla:hasDocument ?doc.
  ?doc dc:title ?docTitle .
  service <https://lila-erc.eu/sparql/lemmaBank/query> {
     ?sameBaseLemma rdfs:label ?sameBaseLemmaLabel.
  }
  
}group by ?sameBaseLemma ?sameBaseLemmaLabel ?docTitle
order by ?sameBaseLemma ?docTitle