prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ontolex: <http://www.w3.org/ns/lemon/ontolex#>
prefix lila: <http://lila-erc.eu/ontologies/lila/>
prefix lilacorpora: <http://lila-erc.eu/ontologies/lila_corpora/>
prefix lime: <http://www.w3.org/ns/lemon/lime#>
prefix marl: <http://www.gsi.dit.upm.es/ontologies/marl/ns#>
prefix powla: <http://purl.org/powla/powla.owl#>
prefix corpora: <http://lila-erc.eu/ontologies/lila_corpora/>
PREFIX ittb: <http://lila-erc.eu/data/corpora/ITTB/id/synFunction/>

# Use the endpoint "LexicalResources"
# List lemmas with a positive polarity in the document

SELECT  ?pnomlemma ?lablemma (count(?pnomlemma) as ?tot)  WHERE {
   <http://lila-erc.eu/data/lexicalResources/LatinAffectus/Lexicon> lime:entry ?lexentry .
    ?lexentry ontolex:canonicalForm ?pnomlemma ;
        ontolex:sense [ marl:hasPolarity marl:Positive ]
      
        SERVICE <http://lila-erc.eu/sparql/corpora/sparql> {
           VALUES ?doc {<XXX>}
          ?t a powla:Terminal ;
             lila:hasLemma ?pnomlemma .
             
          ?t lilacorpora:hasCitStructure/powla:hasDocument ?doc ;

}
    SERVICE <http://lila-erc.eu/sparql/lemmaBank/sparql> {
    ?pnomlemma rdfs:label ?lablemma
  }
}group by ?pnomlemma ?lablemma
order by desc(?tot)